apiVersion: v1
kind: ServiceAccount
metadata:
  name: can-create-context
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cannot-create-context
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: can-create-context
    namespace: default
  - kind: ServiceAccount
    name: cannot-create-context
    namespace: default
roleRef:
  kind: ClusterRole
  name: tekton-aggregate-edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-clusterrolebinding2
subjects:
  - kind: ServiceAccount
    name: can-create-context
    namespace: default
roleRef:
  kind: ClusterRole
  name: setcontext
  apiGroup: rbac.authorization.k8s.io